matrix:
  include:
    - os: linux
      compiler: gcc
    - os: linux
      compiler: clang
    # remove this when we switched to use c++11.
    - os: linux
      compiler: clang
      env: CFLAGS='-std=c++98'
    - os: osx
sudo: false
language: cpp
script:
  - ./misc/ci.py
  - ./configure.py --bootstrap
  - ./ninja all
  - ./ninja_test --gtest_filter=-SubprocessTest.SetWithLots
  - ./misc/ninja_syntax_test.py
  - ./misc/output_test.py
