name: macOS

on:
  pull_request:
  push:
  release:
    types: published

jobs:
  BuildAndTest:
    strategy:
      matrix:
        image: [macos-10.15, macos-11]
        config: [Release, Debug]

    runs-on: ${{ matrix.image }}

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - uses: hendrikmuhs/ccache-action@v1.2
      with:
        key: macos-${{ matrix.image }}-${{ matrix.config }}

    - name: Install dependencies
      run: brew install re2c cmake

    - name: Configure
      env:
        CFLAGS:   ${{ matrix.config == 'Debug' && '-fstack-protector-all -fsanitize=address,bounds,enum,pointer-compare,pointer-subtract -fsanitize-address-use-after-scope' || '' }}
        CXXFLAGS: ${{ matrix.config == 'Debug' && '-fstack-protector-all -fsanitize=address,bounds,enum,pointer-compare,pointer-subtract -fsanitize-address-use-after-scope' || '' }}
        LDFLAGS:  ${{ matrix.config == 'Debug' && '-fsanitize=address,bounds,enum,pointer-compare,pointer-subtract' || '' }}
        MACOSX_DEPLOYMENT_TARGET: 10.12
      run: |
        cmake -Bbuild -GXcode -DCMAKE_OSX_ARCHITECTURES=x86_64 -DCMAKE_CONFIGURATION_TYPES=${{ matrix.config }} -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache 

    - name: Build
      run: |
        cmake --build build --parallel --config ${{ matrix.config }}

    - name: Test
      working-directory: build
      run: |
        ctest --schedule-random --progress --output-on-failure --parallel --no-tests error --build-config ${{ matrix.config }}

  Release:
    runs-on: macos-latest
    if: github.event.action == 'published'
    needs: BuildAndTest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - name: Install dependencies
      run: brew install re2c p7zip cmake

    - name: Configure
      env:
        MACOSX_DEPLOYMENT_TARGET: 10.12
      run: |
        cmake -B build -GXcode -DCMAKE_OSX_ARCHITECTURES="arm64;x86_64" -DCMAKE_CONFIGURATION_TYPES=Release

    - name: Build
      run: |
        cmake --build build --parallel --config Release

    - name: Create archive
      run: |
        mkdir artifact
        7z a artifact/ninja-mac.zip ./build/Release/ninja

    # Upload ninja binary archive as an artifact
    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: ninja-binary-archives
        path: artifact

    - name: Upload release asset
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./artifact/ninja-mac.zip
        asset_name: ninja-mac.zip
        asset_content_type: application/zip
